import Link from "next/link";
import { prisma } from "@/lib/db";
import { SectionTitle, StatusBadge, PriorityBadge, ProgressBar, EmptyState } from "@/components/ui";
import { serviceLabel, SERVICE_LINES } from "@/lib/domain";
import { fmtDate, money } from "@/lib/format";
import { aiEnabled } from "@/lib/ai";
import { createEngagement } from "../actions";

export const dynamic = "force-dynamic";

export default async function EngagementsPage({ searchParams }: { searchParams: { client?: string; new?: string } }) {
  const where = searchParams.client ? { clientId: searchParams.client } : {};
  const [engagements, clients, staff] = await Promise.all([
    prisma.engagement.findMany({
      where,
      include: { client: true, manager: true, _count: { select: { tasks: true } } },
      orderBy: { createdAt: "desc" },
    }),
    prisma.client.findMany({ where: { active: true }, orderBy: { name: "asc" } }),
    prisma.user.findMany({ where: { active: true, role: { not: "CLIENT" } }, orderBy: { name: "asc" } }),
  ]);

  const showForm = searchParams.new !== undefined;

  return (
    <div className="space-y-6">
      <SectionTitle
        title="Engagements"
        subtitle="Every unit of client work, across all service lines"
        action={
          <Link href={showForm ? "/engagements" : "/engagements?new"} className={showForm ? "btn-ghost" : "btn-primary"}>
            {showForm ? "Close" : "+ New engagement"}
          </Link>
        }
      />

      {showForm && (
        <div className="card p-5">
          <div className="mb-4 flex items-center gap-2">
            <h2 className="font-semibold">New engagement</h2>
            <span className={`badge ${aiEnabled() ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>
              {aiEnabled() ? "🤖 Tasks auto-generated by AI" : "🤖 Tasks from built-in playbook"}
            </span>
          </div>
          <form action={createEngagement} className="grid grid-cols-1 gap-3 md:grid-cols-2">
            <div>
              <label className="label">Client *</label>
              <select name="clientId" required className="input" defaultValue={searchParams.client ?? ""}>
                <option value="" disabled>Select client…</option>
                {clients.map((c) => (
                  <option key={c.id} value={c.id}>{c.name}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="label">Service line *</label>
              <select name="serviceLine" required className="input" defaultValue="">
                <option value="" disabled>Select service…</option>
                {SERVICE_LINES.map((s) => (
                  <option key={s.key} value={s.key}>{s.group} · {s.label}</option>
                ))}
              </select>
            </div>
            <div className="md:col-span-2">
              <label className="label">Title *</label>
              <input name="title" required className="input" placeholder="VAT Return — Q2 2026" />
            </div>
            <div>
              <label className="label">Period</label>
              <input name="periodLabel" className="input" placeholder="Q2 2026 / FY2025" />
            </div>
            <div>
              <label className="label">Due date</label>
              <input name="dueDate" type="date" className="input" />
            </div>
            <div>
              <label className="label">Manager</label>
              <select name="managerId" className="input" defaultValue="">
                <option value="">— Me —</option>
                {staff.map((u) => <option key={u.id} value={u.id}>{u.name}</option>)}
              </select>
            </div>
            <div>
              <label className="label">Assign tasks to</label>
              <select name="assigneeId" className="input" defaultValue="">
                <option value="">Unassigned</option>
                {staff.map((u) => <option key={u.id} value={u.id}>{u.name}</option>)}
              </select>
            </div>
            <div>
              <label className="label">Fee (AED)</label>
              <input name="feeAmount" type="number" step="0.01" className="input" />
            </div>
            <div className="md:col-span-2">
              <label className="label">Context for AI (optional)</label>
              <input name="context" className="input" placeholder="e.g. first VAT return after registration, complex group structure" />
            </div>
            <div className="md:col-span-2">
              <button className="btn-primary">Create & generate task plan</button>
            </div>
          </form>
        </div>
      )}

      <div className="card p-5">
        {engagements.length === 0 ? (
          <EmptyState>No engagements yet.</EmptyState>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="text-left text-xs uppercase text-slate-400">
                <tr>
                  <th className="py-2">Reference</th>
                  <th>Client</th>
                  <th>Service</th>
                  <th>Priority</th>
                  <th>Status</th>
                  <th>Due</th>
                  <th>Fee</th>
                  <th className="w-36">Progress</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {engagements.map((e) => (
                  <tr key={e.id} className="hover:bg-slate-50">
                    <td className="py-2.5">
                      <Link href={`/engagements/${e.id}`} className="font-medium text-brand-600 hover:underline">
                        {e.reference}
                      </Link>
                      <div className="text-xs text-slate-400">{e.title}</div>
                    </td>
                    <td>{e.client.name}</td>
                    <td>{serviceLabel(e.serviceLine)}</td>
                    <td><PriorityBadge value={e.priority} /></td>
                    <td><StatusBadge value={e.status} /></td>
                    <td>{fmtDate(e.dueDate)}</td>
                    <td>{money(e.feeAmount, e.currency)}</td>
                    <td>
                      <div className="flex items-center gap-2">
                        <ProgressBar value={e.progress} />
                        <span className="text-xs text-slate-500">{e.progress}%</span>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
